[tool.poetry]
name = "virtool-workflow-pathoscope"
version = "0.1.0"
description = "Virtool's Pathoscope workflow."
authors = ["Blake Smith <blakeinvictoria@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
virtool-workflow = {git = "https://github.com/virtool/virtool-workflow", rev = "develop"}
snapshottest = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest-aiohttp = "^0.3.0"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
